name: jukebox_music_player
description: Music player.
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://docs.flutter.dev/development/accessibility-and-localization/internationalization
  flutter_localizations:
    sdk: flutter

  # Audio packages
  just_audio: ^0.9.34
  flutter_audio_query:
   git:
     url: https://github.com/AkzhanArdaki/flutter_audio_query

  # UI
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^5.1.0

  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Storage
  shared_preferences: ^2.2.1
  
  # Navigator
  go_router: ^10.1.2

  # Utils
  path_provider: ^2.1.1
  logger: ^2.0.2
  freezed: ^2.4.1
  # audiotagger: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  flutter_gen_runner: ^5.3.1
  flutter_gen: ^5.3.1
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  assets:
    enabled: true