name: jukebox_music_player
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Audio packages
  just_audio: ^0.9.20
  flutter_audio_query:
   git:
     url: https://github.com/Mayb3Nots/flutter_audio_query

  l: ^3.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true