name: jukebox_music_player
description: Music player.
publish_to: 'none' 
version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://docs.flutter.dev/development/accessibility-and-localization/internationalization
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils: ^2.8.7

  # Audio packages
  just_audio: ^0.9.38
  just_audio_background: ^0.0.1-beta.11
  # flutter_audio_query:
  #  git:
  #    url: https://github.com/AkzhanArdaki/flutter_audio_query
  jukevault:
    git:
      url: https://github.com/IGraysonI/JukeVault
      ref: main
      path: packages/jukevault

  # UI
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1

  # Database
  shared_preferences: ^2.2.3
  
  # Routing
  octopus: ^0.0.9

  # State management
  control: 0.1.0

  # Firebase packages
  firebase_core: ^2.31.1
  firebase_crashlytics: ^3.5.6

  # Desktop
  win32: ^5.5.1
  window_manager: ^0.3.9

  # Utils
  # audiotagger:
  #   git:
  #     url: https://github.com/IGraysonI/AudioTagger
  #     ref: master 

  collection: any
  async: any
  meta: any
  path: any
  convert: any
  platform_info: ^4.0.2
  stack_trace: ^1.11.1

  # Logger
  l: ^4.0.2


dev_dependencies:
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter
  
  # Integration tests for Flutter
  integration_test:
    sdk: flutter

  # Linter
  flutter_lints: ^4.0.0

  # Codegen
  build_runner: ^2.4.10
  pubspec_generator: '>=4.0.0 <5.0.0'
  flutter_gen_runner: ^5.5.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  shaders:
    - assets/shaders/shimmer.frag

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/localization
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false

flutter_gen:
  output: lib/src/common/constant/
  line_length: 120