name: jukebox_music_player
description: Music player.
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://docs.flutter.dev/development/accessibility-and-localization/internationalization
  flutter_localizations:
    sdk: flutter

  # Audio packages
  just_audio: ^0.9.30
  flutter_audio_query:
   git:
     url: https://github.com/Mayb3Nots/flutter_audio_query

  # UI
  flutter_staggered_grid_view: ^0.6.2
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

  # State management
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  # Storage
  shared_preferences: ^2.0.15
  
  # Navigator
  go_router: ^5.2.4

  # Utils
  path_provider: ^2.0.11
  logger: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/